# Minimal, single-node Loki tuned for Railway
auth_enabled: false

server:
  # Bind to Railway's dynamic $PORT; fall back to 3100 when running locally
  http_listen_port: ${PORT:-3100}
  grpc_listen_port: 9096
  log_level: info
  grpc_server_max_concurrent_streams: 1000

common:
  # Persist data to a Volume mounted at /data (see steps below)
  path_prefix: /data
  storage:
    filesystem:
      chunks_directory: /data/chunks
      rules_directory: /data/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

limits_config:
  allow_structured_metadata: true
  # Optional: uncomment to enforce retention for all tenants
  # retention_period: 168h   # 7 days

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# Optional: pattern matching (can disable if unused)
pattern_ingester:
  enabled: true

# Optional: only needed if you actually run Alertmanager and Ruler
# ruler:
#   alertmanager_url: http://localhost:9093

frontend:
  encoding: protobuf
