auth_enabled: false

server:
  http_listen_port: ${PORT:-3100}
  grpc_listen_port: 9096
  log_level: info
  grpc_server_max_concurrent_streams: 1000

common:
  # <-- match your Railway Volume mount
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

limits_config:
  allow_structured_metadata: true
  # retention_period: 168h  # (optional) keep 7 days

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# Disable if you don't use alerts; otherwise it will try to set up ruler storage
# Comment one of the two blocks below IN:

# (A) Disable ruler entirely (simplest)
# ruler: {}

# (B) Use ruler and keep its files inside the same Volume
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules         # path within the mounted volume
  rule_path: /loki/rules-temp         # temp dir used by ruler
  alertmanager_url: http://localhost:9093
  enable_api: true

frontend:
  encoding: protobuf
